mod animation;
mod aspect_ratio;
mod backdrop;
mod backgrounds;
mod blur;
mod border_radius;
mod border_spacing;
mod borders;
mod brightness;
mod color;
mod contrast;
mod delay;
mod drop_shadow;
mod duration;
mod ease;
mod effects;
mod filters;
mod flex_basis;
mod flexbox;
mod grid;
mod hue_rotate;
mod inset;
mod interactivity;
mod layout;
mod rotate;
mod saturate;
mod scale;
mod scroll_margin;
mod scroll_padding;
mod shadow;
mod sizing;
mod skew;
mod spacing;
mod stroke_width;
mod tables;
mod text_indent;
mod transform_origin;
mod transitions;
mod translate;
mod typography;

use zoecss_config::Preset;

/// Registers all utility rules for the Tailwind CSS v4 preset.
pub fn register_rules(preset: &mut Preset) {
    aspect_ratio::register(preset);
    layout::register(preset);
    flexbox::register(preset);
    grid::register(preset);
    spacing::register(preset);
    sizing::register(preset);
    inset::register(preset);
    scroll_margin::register(preset);
    scroll_padding::register(preset);
    border_spacing::register(preset);
    text_indent::register(preset);
    translate::register(preset);
    flex_basis::register(preset);
    typography::register(preset);
    color::register(preset);
    border_radius::register(preset);
    shadow::register(preset);
    blur::register(preset);
    drop_shadow::register(preset);
    filters::register(preset);
    brightness::register(preset);
    contrast::register(preset);
    hue_rotate::register(preset);
    saturate::register(preset);
    backdrop::register(preset);
    animation::register(preset);
    ease::register(preset);
    duration::register(preset);
    delay::register(preset);
    rotate::register(preset);
    scale::register(preset);
    skew::register(preset);
    stroke_width::register(preset);
    borders::register(preset);
    interactivity::register(preset);
    backgrounds::register(preset);
    effects::register(preset);
    tables::register(preset);
    transitions::register(preset);
    transform_origin::register(preset);
}
