[package]
name = "zoecss-preset-tailwindcss4"
version = "0.0.1"
description = "Tailwind CSS v4 preset for ZoeCSS"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zoecss-core = { path = "../zoecss-core" }
zoecss-config = { path = "../zoecss-config" }
regex = "1"

[lib]
