name: CodSpeed

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-codspeed

      - name: Build benchmarks
        run: cargo codspeed build -p zoecss

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run -p zoecss
          mode: simulation
